# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example/edition_features_test.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'example/edition_features_test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#example/edition_features_test.proto\x12\rtest.editions\"0\n\x11\x45xplicitFieldTest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\">\n\x11ImplicitFieldTest\x12\x13\n\x04name\x18\x01 \x01(\tB\x05\xaa\x01\x02\x08\x02\x12\x14\n\x05value\x18\x02 \x01(\x05\x42\x05\xaa\x01\x02\x08\x02\"G\n\x0eMixedFieldTest\x12\x16\n\x0e\x65xplicit_field\x18\x01 \x01(\t\x12\x1d\n\x0eimplicit_field\x18\x02 \x01(\tB\x05\xaa\x01\x02\x08\x02\"A\n\x0c\x45ncodingTest\x12\x13\n\x0bpacked_ints\x18\x01 \x03(\x05\x12\x1c\n\rexpanded_ints\x18\x02 \x03(\x05\x42\x05\xaa\x01\x02\x18\x02\"\xc9\x02\n\x12\x46\x65\x61tureTestRequest\x12\x37\n\rexplicit_test\x18\x01 \x01(\x0b\x32 .test.editions.ExplicitFieldTest\x12\x37\n\rimplicit_test\x18\x02 \x01(\x0b\x32 .test.editions.ImplicitFieldTest\x12\x31\n\nmixed_test\x18\x03 \x01(\x0b\x32\x1d.test.editions.MixedFieldTest\x12*\n\topen_enum\x18\x04 \x01(\x0e\x32\x17.test.editions.OpenEnum\x12.\n\x0b\x63losed_enum\x18\x05 \x01(\x0e\x32\x19.test.editions.ClosedEnum\x12\x32\n\rencoding_test\x18\x06 \x01(\x0b\x32\x1b.test.editions.EncodingTest\"%\n\x13\x46\x65\x61tureTestResponse\x12\x0e\n\x06result\x18\x01 \x01(\t*4\n\x08OpenEnum\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x46IRST\x10\x01\x12\n\n\x06SECOND\x10\x02\x1a\x04:\x02\x10\x01*.\n\nClosedEnum\x12\x08\n\x04ZERO\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x1a\x04:\x02\x10\x02\x32\xc6\x01\n\x12\x45\x64itionTestService\x12U\n\x0cTestFeatures\x12!.test.editions.FeatureTestRequest\x1a\".test.editions.FeatureTestResponse\x12Y\n\x0bGetFeatures\x12!.test.editions.FeatureTestRequest\x1a\".test.editions.FeatureTestResponse\"\x03\x90\x02\x01\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.edition_features_test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPENENUM']._loaded_options = None
  _globals['_OPENENUM']._serialized_options = b':\002\020\001'
  _globals['_CLOSEDENUM']._loaded_options = None
  _globals['_CLOSEDENUM']._serialized_options = b':\002\020\002'
  _globals['_IMPLICITFIELDTEST'].fields_by_name['name']._loaded_options = None
  _globals['_IMPLICITFIELDTEST'].fields_by_name['name']._serialized_options = b'\252\001\002\010\002'
  _globals['_IMPLICITFIELDTEST'].fields_by_name['value']._loaded_options = None
  _globals['_IMPLICITFIELDTEST'].fields_by_name['value']._serialized_options = b'\252\001\002\010\002'
  _globals['_MIXEDFIELDTEST'].fields_by_name['implicit_field']._loaded_options = None
  _globals['_MIXEDFIELDTEST'].fields_by_name['implicit_field']._serialized_options = b'\252\001\002\010\002'
  _globals['_ENCODINGTEST'].fields_by_name['expanded_ints']._loaded_options = None
  _globals['_ENCODINGTEST'].fields_by_name['expanded_ints']._serialized_options = b'\252\001\002\030\002'
  _globals['_EDITIONTESTSERVICE'].methods_by_name['GetFeatures']._loaded_options = None
  _globals['_EDITIONTESTSERVICE'].methods_by_name['GetFeatures']._serialized_options = b'\220\002\001'
  _globals['_OPENENUM']._serialized_start=679
  _globals['_OPENENUM']._serialized_end=731
  _globals['_CLOSEDENUM']._serialized_start=733
  _globals['_CLOSEDENUM']._serialized_end=779
  _globals['_EXPLICITFIELDTEST']._serialized_start=54
  _globals['_EXPLICITFIELDTEST']._serialized_end=102
  _globals['_IMPLICITFIELDTEST']._serialized_start=104
  _globals['_IMPLICITFIELDTEST']._serialized_end=166
  _globals['_MIXEDFIELDTEST']._serialized_start=168
  _globals['_MIXEDFIELDTEST']._serialized_end=239
  _globals['_ENCODINGTEST']._serialized_start=241
  _globals['_ENCODINGTEST']._serialized_end=306
  _globals['_FEATURETESTREQUEST']._serialized_start=309
  _globals['_FEATURETESTREQUEST']._serialized_end=638
  _globals['_FEATURETESTRESPONSE']._serialized_start=640
  _globals['_FEATURETESTRESPONSE']._serialized_end=677
  _globals['_EDITIONTESTSERVICE']._serialized_start=782
  _globals['_EDITIONTESTSERVICE']._serialized_end=980
# @@protoc_insertion_point(module_scope)
