# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example/eliza.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'example/eliza.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65xample/eliza.proto\x12\x13\x63onnectrpc.eliza.v1\"\x1e\n\nSayRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\"\x1f\n\x0bSayResponse\x12\x10\n\x08sentence\x18\x01 \x01(\t\"#\n\x0f\x43onverseRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\"$\n\x10\x43onverseResponse\x12\x10\n\x08sentence\x18\x01 \x01(\t\" \n\x10IntroduceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"%\n\x11IntroduceResponse\x12\x10\n\x08sentence\x18\x01 \x01(\t2\x9c\x02\n\x0c\x45lizaService\x12M\n\x03Say\x12\x1f.connectrpc.eliza.v1.SayRequest\x1a .connectrpc.eliza.v1.SayResponse\"\x03\x90\x02\x01\x12]\n\x08\x43onverse\x12$.connectrpc.eliza.v1.ConverseRequest\x1a%.connectrpc.eliza.v1.ConverseResponse\"\x00(\x01\x30\x01\x12^\n\tIntroduce\x12%.connectrpc.eliza.v1.IntroduceRequest\x1a&.connectrpc.eliza.v1.IntroduceResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.eliza_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELIZASERVICE'].methods_by_name['Say']._loaded_options = None
  _globals['_ELIZASERVICE'].methods_by_name['Say']._serialized_options = b'\220\002\001'
  _globals['_SAYREQUEST']._serialized_start=44
  _globals['_SAYREQUEST']._serialized_end=74
  _globals['_SAYRESPONSE']._serialized_start=76
  _globals['_SAYRESPONSE']._serialized_end=107
  _globals['_CONVERSEREQUEST']._serialized_start=109
  _globals['_CONVERSEREQUEST']._serialized_end=144
  _globals['_CONVERSERESPONSE']._serialized_start=146
  _globals['_CONVERSERESPONSE']._serialized_end=182
  _globals['_INTRODUCEREQUEST']._serialized_start=184
  _globals['_INTRODUCEREQUEST']._serialized_end=216
  _globals['_INTRODUCERESPONSE']._serialized_start=218
  _globals['_INTRODUCERESPONSE']._serialized_end=255
  _globals['_ELIZASERVICE']._serialized_start=258
  _globals['_ELIZASERVICE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
