# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example/haberdasher_edition_2023.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'example/haberdasher_edition_2023.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&example/haberdasher_edition_2023.proto\x12\x18i2y.connecpy.example2023\"C\n\x03Hat\x12\x12\n\x04size\x18\x01 \x01(\x05R\x04size\x12\x14\n\x05\x63olor\x18\x02 \x01(\tR\x05\x63olor\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\"@\n\x04Size\x12\x16\n\x06inches\x18\x01 \x01(\x05R\x06inches\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription2\\\n\x0bHaberdasher\x12M\n\x07MakeHat\x12\x1e.i2y.connecpy.example2023.Size\x1a\x1d.i2y.connecpy.example2023.Hat\"\x03\x90\x02\x01\x42\rZ\x0b\x65xample2023b\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.haberdasher_edition_2023_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013example2023'
  _globals['_HABERDASHER'].methods_by_name['MakeHat']._loaded_options = None
  _globals['_HABERDASHER'].methods_by_name['MakeHat']._serialized_options = b'\220\002\001'
  _globals['_HAT']._serialized_start=68
  _globals['_HAT']._serialized_end=135
  _globals['_SIZE']._serialized_start=137
  _globals['_SIZE']._serialized_end=201
  _globals['_HABERDASHER']._serialized_start=203
  _globals['_HABERDASHER']._serialized_end=295
# @@protoc_insertion_point(module_scope)
