# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: haberdasher_edition_2023.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 1, "", "haberdasher_edition_2023.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1ehaberdasher_edition_2023.proto\x12\x18i2y.connecpy.example2023"0\n\x03Hat\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t"+\n\x04Size\x12\x0e\n\x06inches\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\\\n\x0bHaberdasher\x12M\n\x07MakeHat\x12\x1e.i2y.connecpy.example2023.Size\x1a\x1d.i2y.connecpy.example2023.Hat"\x03\x90\x02\x01\x42\rZ\x0b\x65xample2023b\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "haberdasher_edition_2023_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\013example2023"
    _globals["_HABERDASHER"].methods_by_name["MakeHat"]._loaded_options = None
    _globals["_HABERDASHER"].methods_by_name[
        "MakeHat"
    ]._serialized_options = b"\220\002\001"
    _globals["_HAT"]._serialized_start = 60
    _globals["_HAT"]._serialized_end = 108
    _globals["_SIZE"]._serialized_start = 110
    _globals["_SIZE"]._serialized_end = 153
    _globals["_HABERDASHER"]._serialized_start = 155
    _globals["_HABERDASHER"]._serialized_end = 247
# @@protoc_insertion_point(module_scope)
