# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: haberdasher.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11haberdasher.proto\x12\x11i2y.conpy.example\">\n\x03Hat\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x11\n\x04name\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\"\x16\n\x04Size\x12\x0e\n\x06inches\x18\x01 \x01(\x05\x32I\n\x0bHaberdasher\x12:\n\x07MakeHat\x12\x17.i2y.conpy.example.Size\x1a\x16.i2y.conpy.example.HatB\tZ\x07\x65xampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'haberdasher_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007example'
  _globals['_HAT']._serialized_start=40
  _globals['_HAT']._serialized_end=102
  _globals['_SIZE']._serialized_start=104
  _globals['_SIZE']._serialized_end=126
  _globals['_HABERDASHER']._serialized_start=128
  _globals['_HABERDASHER']._serialized_end=201
# @@protoc_insertion_point(module_scope)
