# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: haberdasher.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'haberdasher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11haberdasher.proto\x12\x14i2y.connecpy.example\x1a\x1bgoogle/protobuf/empty.proto\"R\n\x03Hat\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x11\n\x04name\x18\x03 \x01(\tH\x00\x88\x01\x01\x1a\x12\n\x04Part\x12\n\n\x02id\x18\x01 \x01(\tB\x07\n\x05_name\"+\n\x04Size\x12\x0e\n\x06inches\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\xc9\x03\n\x0bHaberdasher\x12\x45\n\x07MakeHat\x12\x1a.i2y.connecpy.example.Size\x1a\x19.i2y.connecpy.example.Hat\"\x03\x90\x02\x01\x12L\n\x0fMakeFlexibleHat\x12\x1a.i2y.connecpy.example.Size\x1a\x19.i2y.connecpy.example.Hat\"\x00(\x01\x12O\n\x0fMakeSimilarHats\x12\x1a.i2y.connecpy.example.Size\x1a\x19.i2y.connecpy.example.Hat\"\x03\x90\x02\x01\x30\x01\x12N\n\x0fMakeVariousHats\x12\x1a.i2y.connecpy.example.Size\x1a\x19.i2y.connecpy.example.Hat\"\x00(\x01\x30\x01\x12G\n\tListParts\x12\x16.google.protobuf.Empty\x1a\x1e.i2y.connecpy.example.Hat.Part\"\x00\x30\x01\x12;\n\tDoNothing\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\tZ\x07\x65xampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'haberdasher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007example'
  _globals['_HABERDASHER'].methods_by_name['MakeHat']._loaded_options = None
  _globals['_HABERDASHER'].methods_by_name['MakeHat']._serialized_options = b'\220\002\001'
  _globals['_HABERDASHER'].methods_by_name['MakeSimilarHats']._loaded_options = None
  _globals['_HABERDASHER'].methods_by_name['MakeSimilarHats']._serialized_options = b'\220\002\001'
  _globals['_HAT']._serialized_start=72
  _globals['_HAT']._serialized_end=154
  _globals['_HAT_PART']._serialized_start=127
  _globals['_HAT_PART']._serialized_end=145
  _globals['_SIZE']._serialized_start=156
  _globals['_SIZE']._serialized_end=199
  _globals['_HABERDASHER']._serialized_start=202
  _globals['_HABERDASHER']._serialized_end=659
# @@protoc_insertion_point(module_scope)
