package generator

import "text/template"

type ImportStatement struct {
	Name  string
	Alias string
}

type ConnecpyTemplateVariables struct {
	FileName   string
	ModuleName string
	Imports    []ImportStatement
	Services   []*ConnecpyService
}

type ConnecpyService struct {
	Package string
	Name    string
	Comment string
	Methods []*ConnecpyMethod
}

type ConnecpyMethod struct {
	Package       string
	ServiceName   string
	Name          string
	Comment       string
	InputType     string
	OutputType    string
	NoSideEffects bool
}

// ConnecpyTemplate - Template for connecpy server and client
var ConnecpyTemplate = template.Must(template.New("ConnecpyTemplate").Parse(`# -*- coding: utf-8 -*-
# Generated by https://github.com/i2y/connecpy/protoc-gen-connecpy.  DO NOT EDIT!
# source: {{.FileName}}
{{if .Services}}
from typing import Optional, Protocol, Union

import httpx

from connecpy.async_client import AsyncConnecpyClient
from connecpy.base import Endpoint
from connecpy.server import ConnecpyServer
from connecpy.client import ConnecpyClient
from connecpy.context import ServiceContext
from connecpy.types import Headers

{{- range .Imports }}
import {{.Name}} as {{.Alias}}
{{- end}}
{{- end}}
{{- range .Services}}


class {{.Name}}(Protocol):{{- range .Methods }}
    async def {{.Name}}(self, req: {{.InputType}}, ctx: ServiceContext) -> {{.OutputType}}: ...
{{- end }}


class {{.Name}}Server(ConnecpyServer):
    def __init__(self, *, service: {{.Name}}, server_path_prefix=""):
        super().__init__()
        self._prefix = f"{server_path_prefix}/{{.Package}}.{{.Name}}"
        self._endpoints = { {{- range .Methods }}
            "{{.Name}}": Endpoint[{{.InputType}}, {{.OutputType}}](
                service_name="{{.ServiceName}}",
                name="{{.Name}}",
                function=getattr(service, "{{.Name}}"),
                input={{.InputType}},
                output={{.OutputType}},
                allowed_methods={{if .NoSideEffects}}("GET", "POST"){{else}}("POST",){{end}},
            ),{{- end }}
        }

    def serviceName(self):
        return "{{.Package}}.{{.Name}}"
{{- end }}

{{range .Services}}
class {{.Name}}Sync(Protocol):{{- range .Methods }}
    def {{.Name}}(self, req: {{.InputType}}, ctx: ServiceContext) -> {{.OutputType}}: ...
{{- end }}


class {{.Name}}ServerSync(ConnecpyServer):
    def __init__(self, *, service: {{.Name}}Sync, server_path_prefix=""):
        super().__init__()
        self._prefix = f"{server_path_prefix}/{{.Package}}.{{.Name}}"
        self._endpoints = { {{- range .Methods }}
            "{{.Name}}": Endpoint[{{.InputType}}, {{.OutputType}}](
                service_name="{{.ServiceName}}",
                name="{{.Name}}",
                function=getattr(service, "{{.Name}}"),
                input={{.InputType}},
                output={{.OutputType}},
                allowed_methods={{if .NoSideEffects}}("GET", "POST"){{else}}("POST",){{end}},
            ),{{- end }}
        }

    def serviceName(self):
        return "{{.Package}}.{{.Name}}"


class {{.Name}}Client(ConnecpyClient):{{range .Methods}}
    def {{.Name}}(
        self,
        request: {{.InputType}},
        *,
        headers: Optional[Headers] = None,
        timeout_ms: Optional[int] = None,
        server_path_prefix: str = "",
        {{if .NoSideEffects}}use_get: bool = False,{{end}}
    ) -> {{.OutputType}}:
        {{if .NoSideEffects}}method = "GET" if use_get else "POST"{{else}}method = "POST"{{end}}
        return self._make_request(
            url=f"{server_path_prefix}/{{.Package}}.{{.ServiceName}}/{{.Name}}",
            method=method,
            headers=headers,
            timeout_ms=timeout_ms,
            request=request,
            response_class={{.OutputType}},
        )
{{end}}

class Async{{.Name}}Client(AsyncConnecpyClient):{{range .Methods}}
    async def {{.Name}}(
        self,
        request: {{.InputType}},
        *,
        headers: Optional[Headers] = None,
        timeout_ms: Optional[int] = None,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        {{if .NoSideEffects}}use_get: bool = False,{{end}}
    ) -> {{.OutputType}}:
        {{if .NoSideEffects}}method = "GET" if use_get else "POST"{{else}}method = "POST"{{end}}
        return await self._make_request(
            url=f"{server_path_prefix}/{{.Package}}.{{.ServiceName}}/{{.Name}}",
            method=method,
            headers=headers,
            request=request,
            timeout_ms=timeout_ms,
            response_class={{.OutputType}},
            session=session,
        )
{{end}}{{end}}`))
