# -*- coding: utf-8 -*-
# Generated by https://github.com/i2y/connecpy/protoc-gen-connecpy.  DO NOT EDIT!
# source: google/protobuf/empty.proto


from google.protobuf import symbol_database

_sym_db = symbol_database.Default()
