[project]
name = "connect-python-noextras"
version = "0.1.0"

dependencies = [
    "connect-python",
    "connect-python-example",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
]

[tool.ruff]
extend = "../pyproject.toml"
