[project]
name = "connecpy-noextras"
version = "0.1.0"

dependencies = [
    "connecpy",
    "connecpy-example",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.2",
    "pytest-cov",
]

[tool.ruff]
extend = "../pyproject.toml"
