version: 2
dist: ../out
project_name: protoc-gen-connect-python
builds:
  - main: .
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm64
archives:
  - format_overrides:
      - goos: windows
        formats: ["zip"]
release:
  mode: append
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  disable: true
